In [ ]:
import numpy as  np
import pandas as pd

In [2]:
import numpy as  np
import pandas as pd
#1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix. (Score:1) 

a = np.arange(1,11)
mat = a.reshape(2, 5)
print(mat)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [3]:
# Create a NumPy array from 1 to 20

arr = np.arange(1, 21)

# Extract elements between the 5th and 15th index
result = arr[5:15]

print("Original Array:", arr)
print("Extracted Elements:", result)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Extracted Elements: [ 6  7  8  9 10 11 12 13 14 15]


In [4]:
# Create a NumPy array from 1 to 20
arr = np.arange(1, 21)

# Extract elements between the 5th and 15th index
result = arr[5:15]

# Compute mean, median, and standard deviation
mean = np.mean(result)
median = np.median(result)
std_dev = np.std(result)

print("Extracted Elements:", result)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


Extracted Elements: [ 6  7  8  9 10 11 12 13 14 15]
Mean: 10.5
Median: 10.5
Standard Deviation: 2.8722813232690143


In [5]:
# Create a 2D array of shape (3, 4)
x = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 100, 110, 120]])

# Create a 1D array of shape (4,)
y = np.array([1, 2, 3, 4])

# Subtract y from each row of x using broadcasting
result = x - y

print("Array x:")
print(x)

print("\nArray y:")
print(y)

print("\nResult after broadcasting:")
print(result)

Array x:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Array y:
[1 2 3 4]

Result after broadcasting:
[[  9  18  27  36]
 [ 49  58  67  76]
 [ 89  98 107 116]]


In [7]:
# Create a DataFrame
data = {
    "name": ["Amrita", "Tanishq", "Denzel", "Hariharan", "Tracy",
             "sourabh", "Taniya", "Namit", "Tara", "Hareesh"],
    "age": [20, 22, 25, 35, 32, 27, 40, 30, 35, 24],
    "gender": ["Female", "Male", "Male", "Male", "Female",
               "Male", "Female", "Male", "Female", "Male"]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# 1) Add a new column 'occupation'
df["occupation"] = [
    "Programmer", "Manager", "Analyst", "Programmer", "Manager",
    "Analyst", "Programmer", "Manager", "Analyst", "Programmer"
]

print("\nDataFrame after adding Occupation column:")
print(df)

# 2) Select rows where age >= 30
filtered_df = df[df["age"] >= 30]

print("\nRows where age >= 30:")
print(filtered_df)

# 3) Save DataFrame to CSV
df.to_csv("employees.csv", index=False)

# Read the CSV file
new_df = pd.read_csv("employees.csv")

print("\nContents of the CSV file:")
print(new_df)

Original DataFrame:
        name  age  gender
0     Amrita   20  Female
1    Tanishq   22    Male
2     Denzel   25    Male
3  Hariharan   35    Male
4      Tracy   32  Female
5    sourabh   27    Male
6     Taniya   40  Female
7      Namit   30    Male
8       Tara   35  Female
9    Hareesh   24    Male

DataFrame after adding Occupation column:
        name  age  gender  occupation
0     Amrita   20  Female  Programmer
1    Tanishq   22    Male     Manager
2     Denzel   25    Male     Analyst
3  Hariharan   35    Male  Programmer
4      Tracy   32  Female     Manager
5    sourabh   27    Male     Analyst
6     Taniya   40  Female  Programmer
7      Namit   30    Male     Manager
8       Tara   35  Female     Analyst
9    Hareesh   24    Male  Programmer

Rows where age >= 30:
        name  age  gender  occupation
3  Hariharan   35    Male  Programmer
4      Tracy   32  Female     Manager
6     Taniya   40  Female  Programmer
7      Namit   30    Male     Manager
8       Tara   35  F